# Generated by Django 4.0.8 on 2022-10-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': "'main_app'.'order'",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.CharField(editable=False, max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=123, null=True)),
                ('category', models.CharField(blank=True, max_length=63, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'db_table': "'main_app'.'pizza_type'",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.CharField(editable=False, max_length=31, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pizza_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pizzatype')),
            ],
            options={
                'db_table': "'main_app'.'pizzas'",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pizzas')),
            ],
            options={
                'db_table': "'main_app'.'order_details'",
                'managed': True,
            },
        ),
    ]
